// app/layout.tsx

import type { Metadata } from "next";
import { Poppins, Exo_2 } from "next/font/google"; // 1. Import the fonts
import "./globals.css";

// 2. Configure the fonts
const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Include the weights you'll use
  variable: "--font-poppins", // Set up a CSS variable for the main font
});

const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["700", "800"],
  variable: "--font-exo2", // Set up a CSS variable for the logo font
});

export const metadata: Metadata = {
  title: "BhagwaAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 3. Apply the fonts using their CSS variables */}
      <body className={`${poppins.variable} ${exo2.variable} font-sans bg-gray-900`}>
        {children}
      </body>
    </html>
  );
}
